@startuml
title DoconnectAI - Layered Class Diagram

package "Controllers" {
  class AiController
  class AnswerController
  class ChatMessageController
  class ChatRoomController
  class CommentController
  class QuestionController
  class UserController
  class VoteController
}

package "Services" {
  interface IAnswerService
  interface IChatMessageService
  interface IChatRoomService
  interface ICommentService
  interface IQuestionService
  interface IUserService
  interface IVoteService

  class AIClientService
  class AnswerServiceImpl
  class ChatMessageServiceImpl
  class ChatRoomServiceImpl
  class CommentServiceImpl
  class GeminiService
  class QuestionServiceImpl
  class UserServiceImpl
  class VoterServiceImpl
}

package "Repositories" {
  interface AnswerRepo
  interface ChatMessageRepo
  interface ChatRoomRepo
  interface CommentRepo
  interface QuestionRepo
  interface UserRepo
  interface VoteRepo
}

package "Entities" {
  class User
  class Question
  class Answer
  class Comment
  class ChatRoom
  class ChatMessage
  class Vote
}

'-------------------- Controller -> Service --------------------
AiController --> AIClientService

AnswerController --> IAnswerService
ChatMessageController --> IChatMessageService
ChatRoomController --> IChatRoomService
CommentController --> ICommentService
QuestionController --> IQuestionService
VoteController --> IVoteService
UserController --> UserServiceImpl

'-------------------- Interface -> Implementation --------------------
IAnswerService <|.. AnswerServiceImpl
IChatMessageService <|.. ChatMessageServiceImpl
IChatRoomService <|.. ChatRoomServiceImpl
ICommentService <|.. CommentServiceImpl
IQuestionService <|.. QuestionServiceImpl
IUserService <|.. UserServiceImpl
IVoteService <|.. VoterServiceImpl

'-------------------- Service -> Repository --------------------
AnswerServiceImpl --> AnswerRepo
AnswerServiceImpl --> QuestionRepo
AnswerServiceImpl --> UserRepo

ChatMessageServiceImpl --> ChatMessageRepo
ChatMessageServiceImpl --> ChatRoomRepo
ChatMessageServiceImpl --> UserRepo

ChatRoomServiceImpl --> ChatRoomRepo

CommentServiceImpl --> CommentRepo
CommentServiceImpl --> AnswerRepo
CommentServiceImpl --> UserRepo

QuestionServiceImpl --> QuestionRepo
QuestionServiceImpl --> UserRepo

UserServiceImpl --> UserRepo

VoterServiceImpl --> VoteRepo
VoterServiceImpl --> AnswerRepo
VoterServiceImpl --> UserRepo

'-------------------- Repository -> Entity --------------------
AnswerRepo --> Answer
ChatMessageRepo --> ChatMessage
ChatRoomRepo --> ChatRoom
CommentRepo --> Comment
QuestionRepo --> Question
UserRepo --> User
VoteRepo --> Vote

@enduml