@startuml
title User Login Sequence Diagram

actor User

participant UserController
participant UserServiceImpl
participant UserRepo
database Database

User -> UserController : Login(email,password)
UserController -> UserServiceImpl : authenticate(email,password)
UserServiceImpl -> UserRepo : findByEmail(email)
UserRepo -> Database : SELECT user
Database --> UserRepo : User
UserRepo --> UserServiceImpl : User
UserServiceImpl --> UserController : JWT Token
UserController --> User : Login Success

@enduml