INSERT INTO ai_response (id, answer, keyword) VALUES
(1, 'Java is object oriented, platform independent, secure, and supports multithreading.', 'java features'),
(2, 'Spring Boot simplifies Java backend development with auto configuration and embedded servers.', 'spring boot'),
(3, 'React hooks like useState and useEffect allow functional components to manage state and lifecycle.', 'react hooks'),
(4, 'JWT is a stateless authentication method where a token is used to verify users.', 'jwt authentication'),
(5, 'REST APIs allow communication between frontend and backend using HTTP methods like GET, POST, PUT, DELETE.', 'rest api'),
(6, 'Joins combine rows from two or more tables based on related columns like INNER JOIN or LEFT JOIN.', 'mysql joins'),
(7, 'OOPS concepts include encapsulation, inheritance, polymorphism, and abstraction.', 'oops concepts'),
(8, 'Flexbox is a layout system that helps align and distribute space between items in a container.', 'css flexbox'),
(9, 'Promises in JavaScript handle asynchronous operations with then, catch, and async await.', 'javascript promises'),
(10, 'Microservices architecture divides applications into small independent services.', 'microservices'),
(11, 'A chat system allows real time communication between users through messages in chat rooms.', 'chat system'),
(12, 'A question answer platform lets users post questions and receive answers from other users.', 'question answer website'),
(13, 'Voting helps users upvote or downvote answers based on usefulness and quality.', 'vote system'),
(14, 'Accepting an answer marks it as the best solution to a question.', 'accept answer'),
(15, 'Role based access control restricts system access based on user roles like admin or user.', 'role based access'),
(16, 'Java is a high level programming language used for backend applications.', 'java'),
(17, 'React is a JavaScript library for building user interfaces.', 'react'),
(18, 'Spring framework is used to build enterprise Java applications.', 'spring'),
(19, 'APIs allow different systems to communicate with each other.', 'api'),
(20, 'A database stores structured data that can be retrieved and managed easily.', 'database'),
(21, 'A 403 error in JWT usually happens when the token is invalid, expired, or missing in the Authorization header.', 'jwt token'),
(22, '403 Forbidden means your request is understood but not allowed. Check authentication and user roles.', '403 forbidden'),
(23, 'JWT errors occur when the token is expired, malformed, or signature is invalid.', 'jwt error'),
(24, 'If your token is not working, verify it is sent in the Authorization header with Bearer prefix.', 'token not working'),
(25, 'Authorization header must be in format: Bearer <token>. Missing or incorrect format leads to 403 errors.', 'authorization header'),
(26, 'JWT is used for authentication. A 403 error means access is denied due to invalid or missing token.', 'jwt'),
(27, 'Forbidden error (403) usually means lack of permission or invalid authentication token.', 'forbidden error'),
(28, 'Authentication issues may be due to expired tokens, incorrect headers, or invalid credentials.', 'auth issue');