spring.application.name=doconnectai

spring.datasource.url=jdbc:mysql://localhost:3306/doconnectdb

spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

gemini.api.key= AQ.Ab8RN6Jr2-V56F3Q-h34DC30WiZD8RXjfeO6lrvc1THsB5vK6A

logging.level.root=INFO
logging.level.com.doconnectai=DEBUG

logging.file.name=logs/doconnect.log

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

