@startuml
title Add Comment Sequence Diagram

actor User

participant CommentController
participant ICommentService
participant CommentServiceImpl
participant UserRepo
participant AnswerRepo
participant CommentRepo
database Database

User -> CommentController : Add Comment
CommentController -> ICommentService : saveComment(dto)
ICommentService -> CommentServiceImpl : saveComment(dto)

CommentServiceImpl -> UserRepo : findById(userId)
CommentServiceImpl -> AnswerRepo : findById(answerId)

CommentServiceImpl -> CommentRepo : save(comment)
CommentRepo -> Database : INSERT Comment

CommentRepo --> CommentServiceImpl : Comment
CommentServiceImpl --> CommentController : Success
CommentController --> User : Comment Added

@enduml